#!/bin/bash
bambo_dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )
source "$bambo_dir/utils/utils.sh"

scripts=('d' 'git' 'utils')

[[ "$1" == '--help' ]] && print_global_help && exit 0

if [[ " ${scripts[@]} " =~ " ${1} " ]]; then
	# Specified script tag
	script="$1"
	shift
else
	script=d
fi


# First argument is function name
function_name=$1; shift

# Source main script file with functions
script_dir="$bambo_dir/$script"
source $script_dir/${script}.sh

if [[ "$function_name" == '--help' ]]; then
	print_script_help && exit 0
elif ! is_function "$function_name"; then
	[[ -z "$function_name" ]] &&  echo -e "$(color red)Error: no function provided$(color none)" \
		|| echo -e "$(color red)Error: function $(bold)$function_name$(normal)$(color red) undefined"
	exit 1
fi

# Collect function specific arguments
source "$bambo_dir/_src/arguments.sh"

# Call function
$function_name "${args_inline[@]}" "${args_wildcard[@]}"

