#!/bin/bash
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
utils="$script_dir/utils.sh"


source $script_dir/bambo_src/arguments.sh

# Move to closest docker-compose
workdir=$($utils upfind docker-compose.yml)
if [ -z  $workdir ]; then
	case $function_name in
		help|list|df|pruneall|pruneimages|rebuild|runimage|push)
			# Fine without composefile
		;;
		*) # Otherwise exit
			echo 'No docker-compose.yml found!'
			exit 1
		;;
	esac
else
	cd $workdir
fi

# Setup environment
if [ -f '.env' ]; then
	$($utils parseEnv .env)
	if [[ ! -z $DEFAULT_ENV && $set_env == 0 ]]; then
		echo "Default .env $DEFAULT_ENV"
		env=$DEFAULT_ENV
	fi
	if [[ ! -z $DEFAULT_SERVICE && $set_service == 0 ]]; then
		echo "Default .env $DEFAULT_SERVICE"
		service=$DEFAULT_SERVICE
	fi
else
	echo 'No .env file!'
fi

export CURRENT_ID=$(id -u);
export CURRENT_GID=$(id -g);
export CURRENT_ENV=$env

if [ -f '_docker/scripts.sh' ]; then
	source _docker/scripts.sh
fi


# Load functions
source $script_dir/bambo_src/general.sh
source $script_dir/bambo_src/compose.sh

$function_name
