#!/bin/bash
orb_dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )

source "$orb_dir/_orb/orb_wrapper.sh"
source "$orb_dir/_orb/helpers/help.sh"
[[ "$1" == '--help' ]] && print_global_help && exit 0

source "$orb_dir/_orb/helpers/core.sh"
source "$orb_dir/_orb/helpers/bootstrap.sh"
source "$orb_dir/_orb/helpers/dev.sh"
source "$orb_dir/_orb/helpers/text.sh"

scripts=( root git utils )

if [[ " ${scripts[@]} " =~ " ${1} " ]]; then
	# Specified script tag
	script_name="$1"
	shift
else
	script_name=root
fi

# First argument is function name
function_name=$1; shift
script_dir="$orb_dir/$script_name"

source "$orb_dir/_orb/script_file_sourcer.sh"
handle_function_is_help_or_missing
source "$orb_dir/_orb/arguments_collector.sh"
unset_all_functions_except_called_and_wrapper

# Call function
$function_name "${args_inline[@]}" "${args_wildcard[@]}"

