source "$_orb_dir/lib/helpers/extensions.sh"
source "$_orb_dir/lib/helpers/help.sh"
source "$_orb_dir/lib/helpers/current.sh"

source "$_orb_dir/lib/arguments/assignment.sh"
source "$_orb_dir/lib/arguments/collection.sh"
source "$_orb_dir/lib/arguments/declaration.sh"
source "$_orb_dir/lib/arguments/defaults.sh"
source "$_orb_dir/lib/arguments/properties.sh"
source "$_orb_dir/lib/arguments/validation.sh"

source "$_orb_dir/namespaces/core/args_to.sh"
source "$_orb_dir/namespaces/core/argument.sh"
source "$_orb_dir/namespaces/core/debug.sh"
source "$_orb_dir/namespaces/core/error.sh"
source "$_orb_dir/namespaces/core/file.sh"
source "$_orb_dir/namespaces/core/text.sh"
source "$_orb_dir/namespaces/core/utils.sh"

source "$_orb_dir/lib/scripts/orb_extensions.sh"
